on: push

jobs:
  clang-format:
    runs-on: ubuntu-latest
    container: ghcr.io/cpp-linter/clang-tools:18
    steps:
      - uses: actions/checkout@v4
      - run: clang-format --dry-run -Werror VideoPlayer/*.cpp

  clang-tidy:
    runs-on: ubuntu-latest
    container: ghcr.io/cpp-linter/clang-tools:18
    steps:
      - uses: actions/checkout@v4
      - run: clang-tidy VideoPlayer/*.cpp -- -std=c++20
